Repository pbdsce/pb-placements, pull requests merged in 2025-08, with the labels that each got.

#54 authetication fixes
  app/api/directory/search/route.ts
  app/api/member/[type]/[id]/route.ts
  app/api/profile/update/route.ts
  app/profile/[id]/page.tsx
  app/upload/confirm/page.tsx
  lib/db.ts
Labels: Utils, Frontend, size-L

#53 Improve formatting
  app/profile/[id]/page.tsx
  components/profile/certification-section.tsx
  components/profile/experience-section.tsx
  components/profile/export-profile-button.tsx
  components/profile/project-section.tsx
Labels: size-M, Frontend

#57 Fix year issue
  app/api/directory/search/route.ts
  app/directory/page.tsx
  lib/resume-parser.ts
Labels: Utils, Frontend, size-XS

#65 Changes in db reflects on page
  app/api/directory/search/route.ts
  app/directory/page.tsx
Labels: Frontend, size-S

#68 All available skills and domains made visible in the search dropbox
  components/directory/search-filters.tsx
Labels: Frontend, size-XS

#63 fix popup issue
  components/profile/resume-section.tsx
Labels: size-M, Frontend

#73 Sorted experience section acc to dates
  components/profile/experience-section.tsx
Labels: Frontend, size-XS
